bundler_args: "--without development"
before_script:
  - "cp config/database.example.yml config/database.yml"
script: "RAILS_ENV=test bundle exec rake test:ci --trace"
rvm:
  - 1.9.2
notifications:
  irc: "irc.freenode.org#travis"
