:port: 8080
:debug: false
:log_path: log/socky.log
:secret: my_secret_key
:secure: false

# :subscribe_url: http://localhost:3000/socky/subscribe
# :unsubscribe_url: http://localhost:3000/socky/unsubscribe
# :timeout: 3
# :pid_path: /var/run/socky.pid
# :tls_options:
#   :private_key_file: /private/key
#   :cert_chain_file: /ssl/certificate

